params:
  seed: ${...seed}

  algo:
    name: a2c_continuous

  model:
    name: continuous_a2c_logstd

  network:
    name: multi_input_net_replay
    separate: False

    space:
      continuous:
        mu_activation: tanh
        sigma_activation: None
        mu_init:
          name: default
        sigma_init:
          name: const_initializer
          val: 0
        fixed_sigma: True

    linear_projection:
      shape: 16
      activation: elu

    cnn:
      cnn_out:
        shape: [3]
        activation: relu
      type: conv2d
      activation: elu
      initializer:
          name: default
      regularizer:
        name: None
      convs:    
        - filters: 16
          kernel_size: 8
          strides: 5
          padding: 0
        - filters: 16
          kernel_size: 5
          strides: 2
          padding: 0
        - filters: 32
          kernel_size: 3
          strides: 1
          padding: 0

    image_feature_encoder:
      shape: [256]
      activation: elu

    mlp:
      units: [128, 64, 32]
      activation: elu
      d2rl: False

      initializer:
        name: default
      regularizer:
        name: None

  load_checkpoint: ${if:${...checkpoint},True,False} # flag which sets whether to load the checkpoint
  load_path: ${...checkpoint} # path to the checkpoint to load

  config:
    name: ${resolve_default:Bumpybot,${....experiment}}
    full_experiment_name: ${.name}
    env_name: rlgpu
    multi_gpu: ${....multi_gpu}
    mixed_precision: True
    normalize_input: True
    normalize_value: True
    value_bootstrap: True
    num_actors: ${....task.env.numEnvs}
    reward_shaper:
      scale_value: 0.01
    normalize_advantage: True
    gamma: 0.99
    tau: 0.95
    learning_rate: 5e-4
    lr_schedule: adaptive
    kl_threshold: 0.008
    score_to_win: 2000
    max_epochs: ${resolve_default:1000,${....max_iterations}}
    save_best_after: 100
    save_frequency: 100
    print_stats: True
    grad_norm: 1.0
    entropy_coef: 0.0
    truncate_grads: True
    ppo: True
    e_clip: 0.2
    horizon_length: 20 #hz # horizon_length * num_actors * num_agent
    minibatch_size: 10000 #16384 #4096  # need batchsize % minibatch size == 0
    mini_epochs: 5
    critic_coef: 4
    clip_value: True
    seq_len: 4
    bounds_loss_coef: 0.0001
